version: '3.5'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: hw02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
    volumes:
      - ./hw02:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
    depends_on:
      - postgres